// <auto-generated />
using System;
using BlazorPeopleMapping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPeopleMapping.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230208211756_initialMigrate")]
    partial class initialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorPeopleMapping.Models.Name", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NameString")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("BlazorPeopleMapping.Models.PeopleName", b =>
                {
                    b.Property<long>("NameId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("NameId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PeopleNames");
                });

            modelBuilder.Entity("BlazorPeopleMapping.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SSNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BlazorPeopleMapping.Models.PeopleName", b =>
                {
                    b.HasOne("BlazorPeopleMapping.Models.Name", "Name")
                        .WithMany("PeopleNames")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPeopleMapping.Models.Person", "Person")
                        .WithMany("PersonNames")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BlazorPeopleMapping.Models.Name", b =>
                {
                    b.Navigation("PeopleNames");
                });

            modelBuilder.Entity("BlazorPeopleMapping.Models.Person", b =>
                {
                    b.Navigation("PersonNames");
                });
#pragma warning restore 612, 618
        }
    }
}
